export const users = [
  {
    username: "admin",
    name: "Администратор",
    role: "admin",
    permissions: ["*", "object-types:manage"],
  },
  {
    username: "engineer",
    name: "Инженер сетевой",
    role: "engineer",
    permissions: [
      "objects:pole:read",
      "objects:pole:write",
      "objects:fiber_line:read",
      "objects:fiber_line:write",
      "objects:splice:read",
      "objects:splice:write",
      "objects:route:read",
      "objects:route:write",
      "objects:house:read",
      "objects:house:write",
      "objects:equipment:read",
      "objects:equipment:write",
      "object-relations:fiber_line_pole:read",
      "object-relations:fiber_line_pole:write",
      "object-relations:fiber_line_house:read",
      "object-relations:fiber_line_house:write",
      "object-relations:equipment_house:read",
      "object-relations:equipment_house:write",
      "object-relations:equipment_pole:read",
      "object-relations:equipment_pole:write",
    ],
  },
  {
    username: "viewer",
    name: "Наблюдатель",
    role: "viewer",
    permissions: [
      "objects:pole:read",
      "objects:fiber_line:read",
      "objects:splice:read",
      "objects:route:read",
      "objects:house:read",
      "objects:equipment:read",
    ],
  },
];
